// Code generated by amgen-go; DO NOT EDIT.
use adaptivemsg as am;

#[am::message]
pub struct HelloRequest {
    pub who: String,
    pub question: String,
}

#[am::message]
pub struct HelloReply {
    pub answer: String,
    pub internal: HelloInternal,
}

#[am::message]
pub struct HelloInternal {
    pub trace_id: String,
}
